### ISSUE TITLE
Add array initalization

### ISSUE THREAD

**Issue by bit-hack** [bit-hack/ccml#28]
A way is needed to initialize arrays with values, however its unclear what the syntax would be.

```
var my_array[1234] = 10, 12, 13, 14, 16, 16, 17, 17, 12, 1, 1
```

**Comment by 8BitPimp** [comment]
Perhaps a trailing coma can escape the new line character?

```
var my_array[123] = 12,
  13, 15,
  6
```

**Comment by bit-hack** [comment]
Array initialization was integrated now.
