### ISSUE TITLE
Allow newlines to be escaped so we can break over multiple lines if required

### ISSUE THREAD

**Issue by bit-hack** [bit-hack/ccml#29]
Allow new line characters to be escaped so we can split source lines over multiple lines when needed for style reasons.

One reason for this would be to support array initializers proposal:
```
var my_array[16] = \
  1, 2, 3, 4, \
  5, 6, 7, 8, \ 
  8, 10, 11, 12, \
  13, 14, 15, 16
```

**Comment by 8BitPimp** [comment]
This might be redundant if we pursue line breakage only for array initializers.

**Comment by bit-hack** [comment]
Line breaks were included for array initialization, the other place it could be used is for breaking up long strings over multiple lines?
